baseURL = "http://39.106.85.231/"
languageCode = "en-us"
title = "2p1c's blog"
theme = "vintage-web-hugo-theme"
relativeURLs = false
canonifyURLs = true


# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu
[[menu.main]]
  name = "‚ù§Ô∏è‚Äçü©π Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "üìù Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "üë§ About"
  url = "/about/"
  weight = 30

# Theme Parameters
[params]
  # Site Description
  description = "A nostalgic journey through the early web"
  author = "2p1c"

  # Retro Features
  show_browser_chrome = false
  show_status_bar = false
  show_sidebar = true
  show_welcome_message = false
  welcome_message = " 2p1c's blog "

  # Content Display
  show_featured_sections = false
  show_stats = true
  show_retro_elements = false
  show_sharing = true

  # Footer Options
  show_retro_footer = true
  show_build_info = false

  # Sidebar Options
  show_sidebar_stats = true
  show_retro_sidebar = false
  sidebar_content = "Welcome to our retro corner of the internet!"

  # Social Links
  [params.social]
    twitter = "username"
    github = "https://github.com/2p1c"
    linkedin = "username"
    email = "akidforseven@gmail.com"
    mastodon = "https://mastodon.social/@username"
    youtube = "channelname"
    instagram = "username"
    phonenumber = "18617715681"

  # SEO and Analytics
  google_analytics = "G-XXXXXXXXXX"

  # Repository (for edit links)
  repo_url = "https://github.com/2p1c/my-vintage-blog"
  edit_page = true